(require '[clojure.data.json :as json] '[clojure.java.io :as io])
(def content (slurp "interop_utf8.json"))
(def clean-content (if (= \uFEFF (first content)) (subs content 1) content))
(def specs (json/read-str clean-content))
(def functions (get specs "functions"))
(println "Functions count:" (count functions))
(println "Has strlen?" (contains? functions "strlen"))
(when (contains? functions "array_merge")
  (println "array_merge spec:" (get functions "array_merge")))
(println "First 10 functions:" (take 10 (keys functions)))
