<?php

require __DIR__ . '/vendor/autoload.php';
\Cljp\ErrorHandler::register();

$GLOBALS['inc'] = (function($__L_x) { return ($__L_x + 1);});
$inc = &$GLOBALS['inc'];
$GLOBALS['dec'] = (function($__L_x) { return ($__L_x - 1);});
$dec = &$GLOBALS['dec'];
$GLOBALS['identity'] = (function($__L_x) { return $__L_x;});
$identity = &$GLOBALS['identity'];
$GLOBALS['not'] = (function($__L_x) { if ($__L_x) { return false;} else { return true;}});
$not = &$GLOBALS['not'];
$GLOBALS['nil_QMARK_'] = (function($__L_x) { return is_null($__L_x);});
$nil_QMARK_ = &$GLOBALS['nil_QMARK_'];
$GLOBALS['apply'] = (function($__L_f, ...$__L_args) { $__L_flat_args = (call_user_func($GLOBALS['next'], $__L_args) ? array_merge(array_slice($__L_args, 0, -1), call_user_func($GLOBALS['last'], $__L_args)) : call_user_func($GLOBALS['first'], $__L_args));
return call_user_func_array($__L_f, call_user_func('\Clojure\Php\intoArray', $__L_flat_args));});
$apply = &$GLOBALS['apply'];
$GLOBALS['comp'] = (function(...$__L_fs) { $__L_fs = array_reverse($__L_fs);
return (function(...$__L_args) use (&$__L_fs) { $__L_ret = call_user_func($GLOBALS['apply'], call_user_func($GLOBALS['first'], $__L_fs), $__L_args);
$__L_fs = call_user_func($GLOBALS['next'], $__L_fs);
 while(true) { if ($__L_fs) { $__L_ret = call_user_func(call_user_func($GLOBALS['first'], $__L_fs), $__L_ret); $__L_fs = call_user_func($GLOBALS['next'], $__L_fs); continue;} else { return $__L_ret;} break; }
});});
$comp = &$GLOBALS['comp'];
$GLOBALS['partial'] = (function($__L_f, ...$__L_args) { return (function(...$__L_more) use (&$__L_args, &$__L_f) { return call_user_func($GLOBALS['apply'], $__L_f, array_merge($__L_args, $__L_more));});});
$partial = &$GLOBALS['partial'];
$GLOBALS['count'] = (function($__L_coll) { if (call_user_func($GLOBALS['nil_QMARK_'], $__L_coll)) { return 0;} else { return count($__L_coll);}});
$count = &$GLOBALS['count'];
$GLOBALS['seq'] = (function($__L_coll) { if (call_user_func($GLOBALS['nil_QMARK_'], $__L_coll)) { return null;} else { if (is_array($__L_coll)) { if ((0 === count($__L_coll))) { return null;} else { return $__L_coll;}} else { if (method_exists($__L_coll, 'seq')) { return $__L_coll->seq();} else { return $__L_coll;}}}});
$seq = &$GLOBALS['seq'];
$GLOBALS['first'] = (function($__L_coll) { if (call_user_func($GLOBALS['nil_QMARK_'], $__L_coll)) { return null;} else { if (is_array($__L_coll)) { if ((0 === count($__L_coll))) { return null;} else { return reset($__L_coll);}} else { return $__L_coll->first();}}});
$first = &$GLOBALS['first'];
$GLOBALS['rest'] = (function($__L_coll) { if (call_user_func($GLOBALS['nil_QMARK_'], $__L_coll)) { return \Clojure\Php\vec();} else { if (is_array($__L_coll)) { return array_slice($__L_coll, 1);} else { return $__L_coll->rest();}}});
$rest = &$GLOBALS['rest'];
$GLOBALS['next'] = (function($__L_coll) { if (call_user_func($GLOBALS['nil_QMARK_'], $__L_coll)) { return null;} else { $__L_r = call_user_func($GLOBALS['rest'], $__L_coll);
return call_user_func($GLOBALS['seq'], $__L_r);}});
$next = &$GLOBALS['next'];
$GLOBALS['cons'] = (function($__L_x, $__L_coll) { return call_user_func('\Clojure\Php\cons', $__L_x, $__L_coll);});
$cons = &$GLOBALS['cons'];
$GLOBALS['vector'] = (function(...$__L_args) { return call_user_func('\Clojure\Php\vec', $__L_args);});
$vector = &$GLOBALS['vector'];
$GLOBALS['conj'] = (function(...$__args) { $__n = count($__args); if ($__n == 2) { $__L_coll = $__args[0]; $__L_x = $__args[1]; return call_user_func('\Clojure\Php\conj', $__L_coll, $__L_x); } else if ($__n >= 2) { $__L_coll = $__args[0]; $__L_x = $__args[1]; $__L_xs = array_slice($__args, 2); return call_user_func($GLOBALS['reduce'], $GLOBALS['conj'], call_user_func($GLOBALS['conj'], $__L_coll, $__L_x), $__L_xs); } else { throw new \InvalidArgumentException('Wrong number of args: ' . $__n); } });
$conj = &$GLOBALS['conj'];
$GLOBALS['reduced'] = (function($__L_x) { return call_user_func('\Clojure\Php\reduced', $__L_x);});
$reduced = &$GLOBALS['reduced'];
$GLOBALS['reduced_QMARK_'] = (function($__L_x) { return call_user_func('\Clojure\Php\isReduced', $__L_x);});
$reduced_QMARK_ = &$GLOBALS['reduced_QMARK_'];
$GLOBALS['unreduced'] = (function($__L_x) { if (call_user_func($GLOBALS['reduced_QMARK_'], $__L_x)) { return call_user_func('\Clojure\Php\unreduced', $__L_x);} else { return $__L_x;}});
$unreduced = &$GLOBALS['unreduced'];
$GLOBALS['reduce'] = (function(...$__args) { $__n = count($__args); if ($__n == 3) { $__L_f = $__args[0]; $__L_val = $__args[1]; $__L_coll = $__args[2]; $__L_val = $__L_val;
$__L_coll = $__L_coll;
 while(true) { if (call_user_func($GLOBALS['seq'], $__L_coll)) { $__L_ret = call_user_func($__L_f, $__L_val, call_user_func($GLOBALS['first'], $__L_coll));
if (call_user_func($GLOBALS['reduced_QMARK_'], $__L_ret)) { return call_user_func($GLOBALS['unreduced'], $__L_ret);} else { $__L_val = $__L_ret; $__L_coll = call_user_func($GLOBALS['next'], $__L_coll); continue;}} else { return $__L_val;} break; }
 } else if ($__n == 2) { $__L_f = $__args[0]; $__L_coll = $__args[1]; if (call_user_func($GLOBALS['seq'], $__L_coll)) { return call_user_func($GLOBALS['reduce'], $__L_f, call_user_func($GLOBALS['first'], $__L_coll), call_user_func($GLOBALS['next'], $__L_coll));} else { return call_user_func($__L_f);} } else { throw new \InvalidArgumentException('Wrong number of args: ' . $__n); } });
$reduce = &$GLOBALS['reduce'];
$GLOBALS['reduce_kv'] = (function($__L_f, $__L_init, $__L_coll) { if (call_user_func($GLOBALS['nil_QMARK_'], $__L_coll)) { return $__L_init;} else { $__L_acc = $__L_init;
$__L_ks = call_user_func($GLOBALS['keys'], $__L_coll);
 while(true) { if (call_user_func($GLOBALS['seq'], $__L_ks)) { $__L_k = call_user_func($GLOBALS['first'], $__L_ks);
$__L_ret = call_user_func($__L_f, $__L_acc, $__L_k, call_user_func($GLOBALS['get'], $__L_coll, $__L_k));
if (call_user_func($GLOBALS['reduced_QMARK_'], $__L_ret)) { return call_user_func($GLOBALS['unreduced'], $__L_ret);} else { $__L_acc = $__L_ret; $__L_ks = call_user_func($GLOBALS['next'], $__L_ks); continue;}} else { return $__L_acc;} break; }
}});
$reduce_kv = &$GLOBALS['reduce_kv'];
$GLOBALS['last'] = (function($__L_coll) { $__L_coll = $__L_coll;
 while(true) { if (call_user_func($GLOBALS['next'], $__L_coll)) { $__L_coll = call_user_func($GLOBALS['next'], $__L_coll); continue;} else { return call_user_func($GLOBALS['first'], $__L_coll);} break; }
});
$last = &$GLOBALS['last'];
$GLOBALS['second'] = (function($__L_coll) { return call_user_func($GLOBALS['first'], call_user_func($GLOBALS['next'], $__L_coll));});
$second = &$GLOBALS['second'];
$GLOBALS['map'] = (function($__L_f, $__L_coll) { return (new \Clojure\Php\LazySeq((function() use (&$__L_coll, &$__L_f) { if (call_user_func($GLOBALS['seq'], $__L_coll)) { return call_user_func($GLOBALS['cons'], call_user_func($__L_f, call_user_func($GLOBALS['first'], $__L_coll)), call_user_func($GLOBALS['map'], $__L_f, call_user_func($GLOBALS['next'], $__L_coll)));}})));});
$map = &$GLOBALS['map'];
$GLOBALS['filter'] = (function($__L_pred, $__L_coll) { return (new \Clojure\Php\LazySeq((function() use (&$__L_pred, &$__L_coll) { if (call_user_func($GLOBALS['seq'], $__L_coll)) { $__L_x = call_user_func($GLOBALS['first'], $__L_coll);
if (call_user_func($__L_pred, $__L_x)) { return call_user_func($GLOBALS['cons'], $__L_x, call_user_func($GLOBALS['filter'], $__L_pred, call_user_func($GLOBALS['next'], $__L_coll)));} else { return call_user_func($GLOBALS['filter'], $__L_pred, call_user_func($GLOBALS['next'], $__L_coll));}}})));});
$filter = &$GLOBALS['filter'];
$GLOBALS['mapv'] = (function($__L_f, $__L_coll) { 'Eager version of map - returns a vector';
$__L_result = \Clojure\Php\vec();
$__L_coll = $__L_coll;
 while(true) { if (call_user_func($GLOBALS['seq'], $__L_coll)) { $__L_result = call_user_func($GLOBALS['conj'], $__L_result, call_user_func($__L_f, call_user_func($GLOBALS['first'], $__L_coll))); $__L_coll = call_user_func($GLOBALS['next'], $__L_coll); continue;} else { return $__L_result;} break; }
});
$mapv = &$GLOBALS['mapv'];
$GLOBALS['filterv'] = (function($__L_pred, $__L_coll) { 'Eager version of filter - returns a vector';
$__L_result = \Clojure\Php\vec();
$__L_coll = $__L_coll;
 while(true) { if (call_user_func($GLOBALS['seq'], $__L_coll)) { $__L_x = call_user_func($GLOBALS['first'], $__L_coll);
$__L_result = (call_user_func($__L_pred, $__L_x) ? call_user_func($GLOBALS['conj'], $__L_result, $__L_x) : $__L_result); $__L_coll = call_user_func($GLOBALS['next'], $__L_coll); continue;} else { return $__L_result;} break; }
});
$filterv = &$GLOBALS['filterv'];
$GLOBALS['remove'] = (function($__L_pred, $__L_coll) { return call_user_func($GLOBALS['filter'], (function($__L_x) use (&$__L_pred, &$__L_coll) { return call_user_func($GLOBALS['not'], call_user_func($__L_pred, $__L_x));}), $__L_coll);});
$remove = &$GLOBALS['remove'];
$GLOBALS['mapcat'] = (function($__L_f, $__L_coll) { return call_user_func($GLOBALS['apply'], $GLOBALS['concat'], call_user_func($GLOBALS['map'], $__L_f, $__L_coll));});
$mapcat = &$GLOBALS['mapcat'];
$GLOBALS['map_indexed'] = (function($__L_f, $__L_coll) { $__L_result = \Clojure\Php\vec();
$__L_idx = 0;
$__L_coll = $__L_coll;
 while(true) { if (call_user_func($GLOBALS['seq'], $__L_coll)) { $__L_result = call_user_func($GLOBALS['conj'], $__L_result, call_user_func($__L_f, $__L_idx, call_user_func($GLOBALS['first'], $__L_coll))); $__L_idx = call_user_func($GLOBALS['inc'], $__L_idx); $__L_coll = call_user_func($GLOBALS['next'], $__L_coll); continue;} else { return $__L_result;} break; }
});
$map_indexed = &$GLOBALS['map_indexed'];
$GLOBALS['keep'] = (function($__L_f, $__L_coll) { $__L_result = \Clojure\Php\vec();
$__L_coll = $__L_coll;
 while(true) { if (call_user_func($GLOBALS['seq'], $__L_coll)) { $__L_v = call_user_func($__L_f, call_user_func($GLOBALS['first'], $__L_coll));
$__L_result = (call_user_func($GLOBALS['nil_QMARK_'], $__L_v) ? $__L_result : call_user_func($GLOBALS['conj'], $__L_result, $__L_v)); $__L_coll = call_user_func($GLOBALS['next'], $__L_coll); continue;} else { return $__L_result;} break; }
});
$keep = &$GLOBALS['keep'];
$GLOBALS['keep_indexed'] = (function($__L_f, $__L_coll) { $__L_result = \Clojure\Php\vec();
$__L_idx = 0;
$__L_coll = $__L_coll;
 while(true) { if (call_user_func($GLOBALS['seq'], $__L_coll)) { $__L_v = call_user_func($__L_f, $__L_idx, call_user_func($GLOBALS['first'], $__L_coll));
$__L_result = (call_user_func($GLOBALS['nil_QMARK_'], $__L_v) ? $__L_result : call_user_func($GLOBALS['conj'], $__L_result, $__L_v)); $__L_idx = call_user_func($GLOBALS['inc'], $__L_idx); $__L_coll = call_user_func($GLOBALS['next'], $__L_coll); continue;} else { return $__L_result;} break; }
});
$keep_indexed = &$GLOBALS['keep_indexed'];
$GLOBALS['flatten'] = (function($__L_coll) { $__L_result = \Clojure\Php\vec();
$__L_coll = $__L_coll;
 while(true) { if (call_user_func($GLOBALS['seq'], $__L_coll)) { $__L_x = call_user_func($GLOBALS['first'], $__L_coll);
if ((is_array($__L_x) ? is_array($__L_x) : call_user_func($GLOBALS['coll_QMARK_'], $__L_x))) { $__L_result = call_user_func($GLOBALS['into'], $__L_result, call_user_func($GLOBALS['flatten'], $__L_x)); $__L_coll = call_user_func($GLOBALS['next'], $__L_coll); continue;} else { $__L_result = call_user_func($GLOBALS['conj'], $__L_result, $__L_x); $__L_coll = call_user_func($GLOBALS['next'], $__L_coll); continue;}} else { return $__L_result;} break; }
});
$flatten = &$GLOBALS['flatten'];
$GLOBALS['interleave'] = (function($__L_c1, $__L_c2) { $__L_result = \Clojure\Php\vec();
$__L_s1 = $__L_c1;
$__L_s2 = $__L_c2;
 while(true) { if ((call_user_func($GLOBALS['seq'], $__L_s1) ? call_user_func($GLOBALS['seq'], $__L_s2) : null)) { $__L_result = call_user_func($GLOBALS['conj'], call_user_func($GLOBALS['conj'], $__L_result, call_user_func($GLOBALS['first'], $__L_s1)), call_user_func($GLOBALS['first'], $__L_s2)); $__L_s1 = call_user_func($GLOBALS['next'], $__L_s1); $__L_s2 = call_user_func($GLOBALS['next'], $__L_s2); continue;} else { return $__L_result;} break; }
});
$interleave = &$GLOBALS['interleave'];
$GLOBALS['interpose'] = (function($__L_sep, $__L_coll) { if (call_user_func($GLOBALS['seq'], $__L_coll)) { $__L_result = \Clojure\Php\vec(call_user_func($GLOBALS['first'], $__L_coll));
$__L_coll = call_user_func($GLOBALS['next'], $__L_coll);
 while(true) { if (call_user_func($GLOBALS['seq'], $__L_coll)) { $__L_result = call_user_func($GLOBALS['conj'], call_user_func($GLOBALS['conj'], $__L_result, $__L_sep), call_user_func($GLOBALS['first'], $__L_coll)); $__L_coll = call_user_func($GLOBALS['next'], $__L_coll); continue;} else { return $__L_result;} break; }
} else { return \Clojure\Php\vec();}});
$interpose = &$GLOBALS['interpose'];
$GLOBALS['_EQ_'] = (function(...$__L_args) { if ((count($__L_args) < 2)) { return true;} else { $__L_first_arg = array_shift($__L_args);
$__L_args = $__L_args;
 while(true) { if (call_user_func($GLOBALS['seq'], $__L_args)) { if (call_user_func('\Clojure\Php\equals', $__L_first_arg, call_user_func($GLOBALS['first'], $__L_args))) { $__L_args = call_user_func($GLOBALS['next'], $__L_args); continue;}} else { return true;} break; }
}});
$_EQ_ = &$GLOBALS['_EQ_'];
$GLOBALS['not_EQ_'] = (function(...$__L_args) { return call_user_func($GLOBALS['not'], call_user_func($GLOBALS['apply'], $GLOBALS['_EQ_'], $__L_args));});
$not_EQ_ = &$GLOBALS['not_EQ_'];
$GLOBALS['atom'] = (function($__L_x) { return (new \Clojure\Php\Atom($__L_x));});
$atom = &$GLOBALS['atom'];
$GLOBALS['deref'] = (function($__L_x) { return $__L_x->deref();});
$deref = &$GLOBALS['deref'];
$GLOBALS['reset_BANG_'] = (function($__L_x, $__L_newval) { $__L_x->set($__L_newval);
return $__L_newval;});
$reset_BANG_ = &$GLOBALS['reset_BANG_'];
$GLOBALS['swap_BANG_'] = (function($__L_x, $__L_f, ...$__L_args) { $__L_old = $__L_x->deref();
$__L_new = call_user_func($GLOBALS['apply'], $__L_f, $__L_old, $__L_args);
$__L_x->set($__L_new);
return $__L_new;});
$swap_BANG_ = &$GLOBALS['swap_BANG_'];
$GLOBALS['assoc'] = (function($__L_map, $__L_key, $__L_val, ...$__L_kvs) { $__L_m = call_user_func('\Clojure\Php\assoc', $__L_map, $__L_key, $__L_val);
if ($__L_kvs) { return call_user_func($GLOBALS['apply'], $GLOBALS['assoc'], $__L_m, $__L_kvs);} else { return $__L_m;}});
$assoc = &$GLOBALS['assoc'];
$GLOBALS['update'] = (function($__L_m, $__L_k, $__L_f, ...$__L_args) { return call_user_func($GLOBALS['assoc'], $__L_m, $__L_k, call_user_func($GLOBALS['apply'], $__L_f, call_user_func($GLOBALS['get'], $__L_m, $__L_k), $__L_args));});
$update = &$GLOBALS['update'];
$GLOBALS['get'] = (function(...$__args) { $__n = count($__args); if ($__n == 3) { $__L_m = $__args[0]; $__L_k = $__args[1]; $__L_not_found = $__args[2]; $__L_val = call_user_func('\Clojure\Php\get', $__L_m, $__L_k);
if (call_user_func($GLOBALS['nil_QMARK_'], $__L_val)) { return $__L_not_found;} else { return $__L_val;} } else if ($__n == 2) { $__L_m = $__args[0]; $__L_k = $__args[1]; return call_user_func('\Clojure\Php\get', $__L_m, $__L_k); } else { throw new \InvalidArgumentException('Wrong number of args: ' . $__n); } });
$get = &$GLOBALS['get'];
$GLOBALS['str'] = (function(...$__L_args) { return implode('', $__L_args);});
$str = &$GLOBALS['str'];
$GLOBALS['print'] = (function(...$__L_more) { return print(call_user_func($GLOBALS['apply'], $GLOBALS['str'], $__L_more));});
$print = &$GLOBALS['print'];
$GLOBALS['println'] = (function(...$__L_more) { print(call_user_func($GLOBALS['apply'], $GLOBALS['str'], $__L_more));
return print(PHP_EOL);});
$println = &$GLOBALS['println'];
$GLOBALS['pr_str'] = (function(...$__L_xs) { 'Returns a string containing the printed representation of xs (EDN format)';
return implode(' ', call_user_func('\Clojure\Php\toArray', call_user_func($GLOBALS['map'], (function($__L_x) use (&$__L_xs) { return call_user_func('\Clojure\Php\prStr', $__L_x);}), $__L_xs)));});
$pr_str = &$GLOBALS['pr_str'];
$GLOBALS['prn_str'] = (function(...$__L_xs) { 'Same as pr-str but with a trailing newline';
return call_user_func($GLOBALS['str'], call_user_func($GLOBALS['apply'], $GLOBALS['pr_str'], $__L_xs), PHP_EOL);});
$prn_str = &$GLOBALS['prn_str'];
$GLOBALS['pr'] = (function(...$__L_xs) { 'Prints the object(s) in a machine-readable form';
return print(call_user_func($GLOBALS['apply'], $GLOBALS['pr_str'], $__L_xs));});
$pr = &$GLOBALS['pr'];
$GLOBALS['prn'] = (function(...$__L_xs) { 'Same as pr followed by newline';
print(call_user_func($GLOBALS['apply'], $GLOBALS['pr_str'], $__L_xs));
return print(PHP_EOL);});
$prn = &$GLOBALS['prn'];
$GLOBALS['print_str'] = (function(...$__L_xs) { 'Returns a string of the values printed by print';
return call_user_func($GLOBALS['apply'], $GLOBALS['str'], $__L_xs);});
$print_str = &$GLOBALS['print_str'];
$GLOBALS['_PLUS_'] = (function(...$__L_xs) { return call_user_func($GLOBALS['apply'], $GLOBALS['reduce'], (function($__L_a, $__L_b) use (&$__L_xs) { return ($__L_a + $__L_b);}), 0, $__L_xs);});
$_PLUS_ = &$GLOBALS['_PLUS_'];
$GLOBALS['_'] = (function($__L_x, ...$__L_xs) { if ($__L_xs) { return call_user_func($GLOBALS['apply'], $GLOBALS['reduce'], (function($__L_a, $__L_b) use (&$__L_x, &$__L_xs) { return ($__L_a - $__L_b);}), $__L_x, $__L_xs);} else { return (0 - $__L_x);}});
$_ = &$GLOBALS['_'];
$GLOBALS['_STAR_'] = (function(...$__L_xs) { return call_user_func($GLOBALS['apply'], $GLOBALS['reduce'], (function($__L_a, $__L_b) use (&$__L_xs) { return ($__L_a * $__L_b);}), 1, $__L_xs);});
$_STAR_ = &$GLOBALS['_STAR_'];
$GLOBALS['_SLASH_'] = (function($__L_x, ...$__L_xs) { if ($__L_xs) { return call_user_func($GLOBALS['apply'], $GLOBALS['reduce'], (function($__L_a, $__L_b) use (&$__L_x, &$__L_xs) { return ($__L_a / $__L_b);}), $__L_x, $__L_xs);} else { return (1 / $__L_x);}});
$_SLASH_ = &$GLOBALS['_SLASH_'];
$GLOBALS['mod'] = (function($__L_num, $__L_div) { $__L_m = ($__L_num % $__L_div);
if (((0 === $__L_m) ? (0 === $__L_m) : (($__L_num > 0) === ($__L_div > 0)))) { return $__L_m;} else { return ($__L_m + $__L_div);}});
$mod = &$GLOBALS['mod'];
$GLOBALS['rem'] = (function($__L_num, $__L_div) { return ($__L_num % $__L_div);});
$rem = &$GLOBALS['rem'];
$GLOBALS['quot'] = (function($__L_num, $__L_div) { return intdiv($__L_num, $__L_div);});
$quot = &$GLOBALS['quot'];
$GLOBALS['max'] = (function(...$__args) { $__n = count($__args); if ($__n == 2) { $__L_x = $__args[0]; $__L_y = $__args[1]; if (($__L_x > $__L_y)) { return $__L_x;} else { return $__L_y;} } else if ($__n == 1) { $__L_x = $__args[0]; return $__L_x; } else if ($__n >= 2) { $__L_x = $__args[0]; $__L_y = $__args[1]; $__L_more = array_slice($__args, 2); return call_user_func($GLOBALS['reduce'], $GLOBALS['max'], call_user_func($GLOBALS['max'], $__L_x, $__L_y), $__L_more); } else { throw new \InvalidArgumentException('Wrong number of args: ' . $__n); } });
$max = &$GLOBALS['max'];
$GLOBALS['min'] = (function(...$__args) { $__n = count($__args); if ($__n == 2) { $__L_x = $__args[0]; $__L_y = $__args[1]; if (($__L_x < $__L_y)) { return $__L_x;} else { return $__L_y;} } else if ($__n == 1) { $__L_x = $__args[0]; return $__L_x; } else if ($__n >= 2) { $__L_x = $__args[0]; $__L_y = $__args[1]; $__L_more = array_slice($__args, 2); return call_user_func($GLOBALS['reduce'], $GLOBALS['min'], call_user_func($GLOBALS['min'], $__L_x, $__L_y), $__L_more); } else { throw new \InvalidArgumentException('Wrong number of args: ' . $__n); } });
$min = &$GLOBALS['min'];
$GLOBALS['abs'] = (function($__L_a) { return abs($__L_a);});
$abs = &$GLOBALS['abs'];
$GLOBALS['zero_QMARK_'] = (function($__L_x) { return (0 === $__L_x);});
$zero_QMARK_ = &$GLOBALS['zero_QMARK_'];
$GLOBALS['pos_QMARK_'] = (function($__L_x) { return ($__L_x > 0);});
$pos_QMARK_ = &$GLOBALS['pos_QMARK_'];
$GLOBALS['neg_QMARK_'] = (function($__L_x) { return ($__L_x < 0);});
$neg_QMARK_ = &$GLOBALS['neg_QMARK_'];
$GLOBALS['even_QMARK_'] = (function($__L_n) { return (0 === ($__L_n % 2));});
$even_QMARK_ = &$GLOBALS['even_QMARK_'];
$GLOBALS['odd_QMARK_'] = (function($__L_n) { return (1 === abs(($__L_n % 2)));});
$odd_QMARK_ = &$GLOBALS['odd_QMARK_'];
$GLOBALS['string_QMARK_'] = (function($__L_x) { return is_string($__L_x);});
$string_QMARK_ = &$GLOBALS['string_QMARK_'];
$GLOBALS['int_QMARK_'] = (function($__L_x) { return is_int($__L_x);});
$int_QMARK_ = &$GLOBALS['int_QMARK_'];
$GLOBALS['integer_QMARK_'] = (function($__L_x) { return is_int($__L_x);});
$integer_QMARK_ = &$GLOBALS['integer_QMARK_'];
$GLOBALS['float_QMARK_'] = (function($__L_x) { return is_float($__L_x);});
$float_QMARK_ = &$GLOBALS['float_QMARK_'];
$GLOBALS['number_QMARK_'] = (function($__L_x) { return is_numeric($__L_x);});
$number_QMARK_ = &$GLOBALS['number_QMARK_'];
$GLOBALS['boolean_QMARK_'] = (function($__L_x) { return is_bool($__L_x);});
$boolean_QMARK_ = &$GLOBALS['boolean_QMARK_'];
$GLOBALS['true_QMARK_'] = (function($__L_x) { return ($__L_x === true);});
$true_QMARK_ = &$GLOBALS['true_QMARK_'];
$GLOBALS['false_QMARK_'] = (function($__L_x) { return ($__L_x === false);});
$false_QMARK_ = &$GLOBALS['false_QMARK_'];
$GLOBALS['array_QMARK_'] = (function($__L_x) { return is_array($__L_x);});
$array_QMARK_ = &$GLOBALS['array_QMARK_'];
$GLOBALS['fn_QMARK_'] = (function($__L_x) { return is_callable($__L_x);});
$fn_QMARK_ = &$GLOBALS['fn_QMARK_'];
$GLOBALS['symbol_QMARK_'] = (function($__L_x) { return is_string($__L_x);});
$symbol_QMARK_ = &$GLOBALS['symbol_QMARK_'];
$GLOBALS['keyword_QMARK_'] = (function($__L_x) { return ($__L_x instanceof \Clojure\Php\Kw);});
$keyword_QMARK_ = &$GLOBALS['keyword_QMARK_'];
$GLOBALS['vector_QMARK_'] = (function($__L_x) { return ($__L_x instanceof \Clojure\Php\Vec);});
$vector_QMARK_ = &$GLOBALS['vector_QMARK_'];
$GLOBALS['map_QMARK_'] = (function($__L_x) { return ($__L_x instanceof \Clojure\Php\Map);});
$map_QMARK_ = &$GLOBALS['map_QMARK_'];
$GLOBALS['set_QMARK_'] = (function($__L_x) { return ($__L_x instanceof \Clojure\Php\Set);});
$set_QMARK_ = &$GLOBALS['set_QMARK_'];
$GLOBALS['list_QMARK_'] = (function($__L_x) { return ($__L_x instanceof \Clojure\Php\PList);});
$list_QMARK_ = &$GLOBALS['list_QMARK_'];
$GLOBALS['coll_QMARK_'] = (function($__L_x) { if (call_user_func($GLOBALS['vector_QMARK_'], $__L_x)) { return call_user_func($GLOBALS['vector_QMARK_'], $__L_x);} else { if (call_user_func($GLOBALS['map_QMARK_'], $__L_x)) { return call_user_func($GLOBALS['map_QMARK_'], $__L_x);} else { if (call_user_func($GLOBALS['set_QMARK_'], $__L_x)) { return call_user_func($GLOBALS['set_QMARK_'], $__L_x);} else { if (call_user_func($GLOBALS['list_QMARK_'], $__L_x)) { return call_user_func($GLOBALS['list_QMARK_'], $__L_x);} else { return is_array($__L_x);}}}}});
$coll_QMARK_ = &$GLOBALS['coll_QMARK_'];
$GLOBALS['seq_QMARK_'] = (function($__L_x) { if (call_user_func($GLOBALS['vector_QMARK_'], $__L_x)) { return call_user_func($GLOBALS['vector_QMARK_'], $__L_x);} else { return call_user_func($GLOBALS['list_QMARK_'], $__L_x);}});
$seq_QMARK_ = &$GLOBALS['seq_QMARK_'];
$GLOBALS['empty_QMARK_'] = (function($__L_x) { return (0 === call_user_func($GLOBALS['count'], $__L_x));});
$empty_QMARK_ = &$GLOBALS['empty_QMARK_'];
$GLOBALS['some_QMARK_'] = (function($__L_x) { return call_user_func($GLOBALS['not'], call_user_func($GLOBALS['nil_QMARK_'], $__L_x));});
$some_QMARK_ = &$GLOBALS['some_QMARK_'];
$GLOBALS['keys'] = (function($__L_m) { if (call_user_func($GLOBALS['nil_QMARK_'], $__L_m)) { return null;} else { return call_user_func('\Clojure\Php\keys', $__L_m);}});
$keys = &$GLOBALS['keys'];
$GLOBALS['vals'] = (function($__L_m) { if (call_user_func($GLOBALS['nil_QMARK_'], $__L_m)) { return null;} else { return call_user_func('\Clojure\Php\vals', $__L_m);}});
$vals = &$GLOBALS['vals'];
$GLOBALS['contains_QMARK_'] = (function($__L_coll, $__L_key) { if (call_user_func($GLOBALS['nil_QMARK_'], $__L_coll)) { return false;} else { return call_user_func('\Clojure\Php\contains', $__L_coll, $__L_key);}});
$contains_QMARK_ = &$GLOBALS['contains_QMARK_'];
$GLOBALS['take'] = (function($__L_n, $__L_coll) { $__L_n = $__L_n;
$__L_coll = $__L_coll;
$__L_result = \Clojure\Php\vec();
 while(true) { if ((($__L_n > 0) ? call_user_func($GLOBALS['seq'], $__L_coll) : null)) { $__L_x = call_user_func($GLOBALS['first'], $__L_coll);
$__L_n = call_user_func($GLOBALS['dec'], $__L_n); $__L_coll = call_user_func($GLOBALS['next'], $__L_coll); $__L_result = call_user_func($GLOBALS['conj'], $__L_result, $__L_x); continue;} else { return $__L_result;} break; }
});
$take = &$GLOBALS['take'];
$GLOBALS['drop'] = (function($__L_n, $__L_coll) { $__L_n = $__L_n;
$__L_coll = $__L_coll;
 while(true) { if ((($__L_n > 0) ? call_user_func($GLOBALS['seq'], $__L_coll) : null)) { $__L_n = call_user_func($GLOBALS['dec'], $__L_n); $__L_coll = call_user_func($GLOBALS['next'], $__L_coll); continue;} else { return $__L_coll;} break; }
});
$drop = &$GLOBALS['drop'];
$GLOBALS['take_while'] = (function($__L_pred, $__L_coll) { $__L_coll = $__L_coll;
$__L_result = \Clojure\Php\vec();
 while(true) { if (call_user_func($GLOBALS['seq'], $__L_coll)) { $__L_x = call_user_func($GLOBALS['first'], $__L_coll);
if (call_user_func($__L_pred, $__L_x)) { $__L_coll = call_user_func($GLOBALS['next'], $__L_coll); $__L_result = call_user_func($GLOBALS['conj'], $__L_result, $__L_x); continue;} else { return $__L_result;}} else { return $__L_result;} break; }
});
$take_while = &$GLOBALS['take_while'];
$GLOBALS['drop_while'] = (function($__L_pred, $__L_coll) { $__L_coll = $__L_coll;
 while(true) { if (call_user_func($GLOBALS['seq'], $__L_coll)) { if (call_user_func($__L_pred, call_user_func($GLOBALS['first'], $__L_coll))) { $__L_coll = call_user_func($GLOBALS['next'], $__L_coll); continue;} else { return $__L_coll;}} else { return $__L_coll;} break; }
});
$drop_while = &$GLOBALS['drop_while'];
$GLOBALS['concat'] = (function(...$__L_colls) { return call_user_func($GLOBALS['reduce'], (function($__L_acc, $__L_c) use (&$__L_colls) { $__L_acc = $__L_acc;
$__L_c = $__L_c;
 while(true) { if (call_user_func($GLOBALS['seq'], $__L_c)) { $__L_acc = call_user_func($GLOBALS['conj'], $__L_acc, call_user_func($GLOBALS['first'], $__L_c)); $__L_c = call_user_func($GLOBALS['next'], $__L_c); continue;} else { return $__L_acc;} break; }
}), \Clojure\Php\vec(), $__L_colls);});
$concat = &$GLOBALS['concat'];
$GLOBALS['reverse'] = (function($__L_coll) { $__L_arr = call_user_func('\Clojure\Php\toArray', $__L_coll);
return call_user_func('\Clojure\Php\vector', array_reverse($__L_arr));});
$reverse = &$GLOBALS['reverse'];
$GLOBALS['nth'] = (function(...$__args) { $__n = count($__args); if ($__n == 3) { $__L_coll = $__args[0]; $__L_n = $__args[1]; $__L_not_found = $__args[2]; if (call_user_func($GLOBALS['vector_QMARK_'], $__L_coll)) { if ((($__L_n >= 0) ? ($__L_n < call_user_func($GLOBALS['count'], $__L_coll)) : null)) { return call_user_func('\Clojure\Php\get', $__L_coll, $__L_n);} else { return $__L_not_found;}} else { $__L_coll = $__L_coll;
$__L_n = $__L_n;
 while(true) { if (call_user_func($GLOBALS['seq'], $__L_coll)) { if (($__L_n === 0)) { return call_user_func($GLOBALS['first'], $__L_coll);} else { $__L_coll = call_user_func($GLOBALS['next'], $__L_coll); $__L_n = call_user_func($GLOBALS['dec'], $__L_n); continue;}} else { return $__L_not_found;} break; }
} } else if ($__n == 2) { $__L_coll = $__args[0]; $__L_n = $__args[1]; return call_user_func($GLOBALS['nth'], $__L_coll, $__L_n, null); } else { throw new \InvalidArgumentException('Wrong number of args: ' . $__n); } });
$nth = &$GLOBALS['nth'];
$GLOBALS['range3'] = (function($__L_start, $__L_end, $__L_step) { $__L_n = $__L_start;
$__L_result = \Clojure\Php\vec();
 while(true) { if (($__L_n < $__L_end)) { $__L_current = $__L_n;
$__L_n = ($__L_n + $__L_step); $__L_result = call_user_func($GLOBALS['conj'], $__L_result, $__L_current); continue;} else { return $__L_result;} break; }
});
$range3 = &$GLOBALS['range3'];
$GLOBALS['range'] = (function($__L_end_or_start, ...$__L_args) { if (call_user_func($GLOBALS['nil_QMARK_'], call_user_func($GLOBALS['first'], $__L_args))) { return call_user_func($GLOBALS['range3'], 0, $__L_end_or_start, 1);} else { $__L_end = call_user_func($GLOBALS['first'], $__L_args);
$__L_step = (call_user_func($GLOBALS['second'], $__L_args) ? call_user_func($GLOBALS['second'], $__L_args) : 1);
return call_user_func($GLOBALS['range3'], $__L_end_or_start, $__L_end, $__L_step);}});
$range = &$GLOBALS['range'];
$GLOBALS['repeat'] = (function($__L_n, $__L_x) { $__L_i = $__L_n;
$__L_result = \Clojure\Php\vec();
 while(true) { if (($__L_i > 0)) { $__L_i = call_user_func($GLOBALS['dec'], $__L_i); $__L_result = call_user_func($GLOBALS['conj'], $__L_result, $__L_x); continue;} else { return $__L_result;} break; }
});
$repeat = &$GLOBALS['repeat'];
$GLOBALS['into'] = (function($__L_to, $__L_from) { return call_user_func($GLOBALS['reduce'], $GLOBALS['conj'], $__L_to, $__L_from);});
$into = &$GLOBALS['into'];
$GLOBALS['zipmap'] = (function($__L_keys, $__L_vals) { $__L_m = \Clojure\Php\hashMap();
$__L_ks = $__L_keys;
$__L_vs = $__L_vals;
 while(true) { if ((call_user_func($GLOBALS['seq'], $__L_ks) ? call_user_func($GLOBALS['seq'], $__L_vs) : null)) { $__L_m = call_user_func($GLOBALS['assoc'], $__L_m, call_user_func($GLOBALS['first'], $__L_ks), call_user_func($GLOBALS['first'], $__L_vs)); $__L_ks = call_user_func($GLOBALS['next'], $__L_ks); $__L_vs = call_user_func($GLOBALS['next'], $__L_vs); continue;} else { return $__L_m;} break; }
});
$zipmap = &$GLOBALS['zipmap'];
$GLOBALS['partition'] = (function(...$__args) { $__n = count($__args); if ($__n == 4) { $__L_n = $__args[0]; $__L_step = $__args[1]; $__L_pad = $__args[2]; $__L_coll = $__args[3]; $__L_coll = $__L_coll;
$__L_result = \Clojure\Php\vec();
 while(true) { $__L_chunk = call_user_func($GLOBALS['take'], $__L_n, $__L_coll);
if (($__L_n === call_user_func($GLOBALS['count'], $__L_chunk))) { $__L_coll = call_user_func($GLOBALS['drop'], $__L_step, $__L_coll); $__L_result = call_user_func($GLOBALS['conj'], $__L_result, $__L_chunk); continue;} else { if (call_user_func($GLOBALS['seq'], $__L_chunk)) { return call_user_func($GLOBALS['conj'], $__L_result, call_user_func($GLOBALS['take'], $__L_n, call_user_func($GLOBALS['concat'], $__L_chunk, $__L_pad)));} else { return $__L_result;}} break; }
 } else if ($__n == 3) { $__L_n = $__args[0]; $__L_step = $__args[1]; $__L_coll = $__args[2]; $__L_coll = $__L_coll;
$__L_result = \Clojure\Php\vec();
 while(true) { $__L_chunk = call_user_func($GLOBALS['take'], $__L_n, $__L_coll);
if (($__L_n === call_user_func($GLOBALS['count'], $__L_chunk))) { $__L_coll = call_user_func($GLOBALS['drop'], $__L_step, $__L_coll); $__L_result = call_user_func($GLOBALS['conj'], $__L_result, $__L_chunk); continue;} else { return $__L_result;} break; }
 } else if ($__n == 2) { $__L_n = $__args[0]; $__L_coll = $__args[1]; return call_user_func($GLOBALS['partition'], $__L_n, $__L_n, $__L_coll); } else { throw new \InvalidArgumentException('Wrong number of args: ' . $__n); } });
$partition = &$GLOBALS['partition'];
$GLOBALS['distinct'] = (function($__L_coll) { $__L_coll = $__L_coll;
$__L_seen = \Clojure\Php\hashSet();
$__L_result = \Clojure\Php\vec();
 while(true) { if (call_user_func($GLOBALS['seq'], $__L_coll)) { $__L_x = call_user_func($GLOBALS['first'], $__L_coll);
if (call_user_func($GLOBALS['contains_QMARK_'], $__L_seen, $__L_x)) { $__L_coll = call_user_func($GLOBALS['next'], $__L_coll); $__L_seen = $__L_seen; $__L_result = $__L_result; continue;} else { $__L_coll = call_user_func($GLOBALS['next'], $__L_coll); $__L_seen = call_user_func($GLOBALS['conj'], $__L_seen, $__L_x); $__L_result = call_user_func($GLOBALS['conj'], $__L_result, $__L_x); continue;}} else { return $__L_result;} break; }
});
$distinct = &$GLOBALS['distinct'];
$GLOBALS['group_by'] = (function($__L_f, $__L_coll) { return call_user_func($GLOBALS['reduce'], (function($__L_m, $__L_x) use (&$__L_coll, &$__L_f) { $__L_k = call_user_func($__L_f, $__L_x);
return call_user_func($GLOBALS['update'], $__L_m, $__L_k, (function($__L_v) use (&$__L_x, &$__L_m, &$__L_coll, &$__L_k, &$__L_f) { return call_user_func($GLOBALS['conj'], ($__L_v ? $__L_v : \Clojure\Php\vec()), $__L_x);}));}), \Clojure\Php\hashMap(), $__L_coll);});
$group_by = &$GLOBALS['group_by'];
$GLOBALS['frequencies'] = (function($__L_coll) { return call_user_func($GLOBALS['reduce'], (function($__L_m, $__L_x) use (&$__L_coll) { return call_user_func($GLOBALS['update'], $__L_m, $__L_x, (function($__L_v) use (&$__L_x, &$__L_m, &$__L_coll) { return (($__L_v ? $__L_v : 0) + 1);}));}), \Clojure\Php\hashMap(), $__L_coll);});
$frequencies = &$GLOBALS['frequencies'];
$GLOBALS['sort'] = (function(...$__args) { $__n = count($__args); if ($__n == 2) { $__L_comp = $__args[0]; $__L_coll = $__args[1]; $__L_arr = call_user_func('\Clojure\Php\toArray', $__L_coll);
usort($__L_arr, $__L_comp);
return call_user_func('\Clojure\Php\vector', $__L_arr); } else if ($__n == 1) { $__L_coll = $__args[0]; $__L_arr = call_user_func('\Clojure\Php\toArray', $__L_coll);
sort($__L_arr);
return call_user_func('\Clojure\Php\vector', $__L_arr); } else { throw new \InvalidArgumentException('Wrong number of args: ' . $__n); } });
$sort = &$GLOBALS['sort'];
$GLOBALS['sort_by'] = (function($__L_keyfn, $__L_coll) { $__L_arr = call_user_func('\Clojure\Php\toArray', $__L_coll);
usort($__L_arr, (function($__L_a, $__L_b) use (&$__L_arr, &$__L_coll, &$__L_keyfn) { $__L_ka = call_user_func($__L_keyfn, $__L_a);
$__L_kb = call_user_func($__L_keyfn, $__L_b);
if (($__L_ka < $__L_kb)) { return -1;} else { if (($__L_ka > $__L_kb)) { return 1;} else { return 0;}}}));
return call_user_func('\Clojure\Php\vector', $__L_arr);});
$sort_by = &$GLOBALS['sort_by'];
$GLOBALS['merge'] = (function(...$__L_maps) { return call_user_func($GLOBALS['reduce'], (function($__L_m1, $__L_m2) use (&$__L_maps) { if ($__L_m2) { return call_user_func($GLOBALS['reduce'], (function($__L_m, $__L_kv) use (&$__L_m1, &$__L_maps, &$__L_m2) { return call_user_func($GLOBALS['assoc'], $__L_m, call_user_func($GLOBALS['first'], $__L_kv), call_user_func($GLOBALS['second'], $__L_kv));}), $__L_m1, call_user_func($GLOBALS['seq'], $__L_m2));} else { return $__L_m1;}}), \Clojure\Php\hashMap(), $__L_maps);});
$merge = &$GLOBALS['merge'];
$GLOBALS['get_in'] = (function($__L_m, $__L_ks) { return call_user_func($GLOBALS['reduce'], $GLOBALS['get'], $__L_m, $__L_ks);});
$get_in = &$GLOBALS['get_in'];
$GLOBALS['assoc_in'] = (function($__L_m, $__L_ks, $__L_v) { $__L_k = call_user_func($GLOBALS['first'], $__L_ks);
$__L_ks = call_user_func($GLOBALS['next'], $__L_ks);
if ($__L_ks) { return call_user_func($GLOBALS['assoc'], $__L_m, $__L_k, call_user_func($GLOBALS['assoc_in'], call_user_func($GLOBALS['get'], $__L_m, $__L_k), $__L_ks, $__L_v));} else { return call_user_func($GLOBALS['assoc'], $__L_m, $__L_k, $__L_v);}});
$assoc_in = &$GLOBALS['assoc_in'];
$GLOBALS['update_in'] = (function($__L_m, $__L_ks, $__L_f, ...$__L_args) { $__L_k = call_user_func($GLOBALS['first'], $__L_ks);
$__L_ks = call_user_func($GLOBALS['next'], $__L_ks);
if ($__L_ks) { return call_user_func($GLOBALS['assoc'], $__L_m, $__L_k, call_user_func($GLOBALS['apply'], $GLOBALS['update_in'], call_user_func($GLOBALS['get'], $__L_m, $__L_k), $__L_ks, $__L_f, $__L_args));} else { return call_user_func($GLOBALS['assoc'], $__L_m, $__L_k, call_user_func($GLOBALS['apply'], $__L_f, call_user_func($GLOBALS['get'], $__L_m, $__L_k), $__L_args));}});
$update_in = &$GLOBALS['update_in'];
$GLOBALS['dissoc'] = (function($__L_m, ...$__L_ks) { return call_user_func($GLOBALS['reduce'], (function($__L_m, $__L_k) use (&$__L_ks) { return call_user_func('\Clojure\Php\dissoc', $__L_m, $__L_k);}), $__L_m, $__L_ks);});
$dissoc = &$GLOBALS['dissoc'];
$GLOBALS['select_keys'] = (function($__L_m, $__L_ks) { return call_user_func($GLOBALS['reduce'], (function($__L_result, $__L_k) use (&$__L_ks, &$__L_m) { if (call_user_func($GLOBALS['contains_QMARK_'], $__L_m, $__L_k)) { return call_user_func($GLOBALS['assoc'], $__L_result, $__L_k, call_user_func($GLOBALS['get'], $__L_m, $__L_k));} else { return $__L_result;}}), \Clojure\Php\hashMap(), $__L_ks);});
$select_keys = &$GLOBALS['select_keys'];
$GLOBALS['every_QMARK_'] = (function($__L_pred, $__L_coll) { $__L_coll = $__L_coll;
 while(true) { if (call_user_func($GLOBALS['seq'], $__L_coll)) { if (call_user_func($__L_pred, call_user_func($GLOBALS['first'], $__L_coll))) { $__L_coll = call_user_func($GLOBALS['next'], $__L_coll); continue;}} else { return true;} break; }
});
$every_QMARK_ = &$GLOBALS['every_QMARK_'];
$GLOBALS['some'] = (function($__L_pred, $__L_coll) { $__L_coll = $__L_coll;
 while(true) { if (call_user_func($GLOBALS['seq'], $__L_coll)) { $__L_result = call_user_func($__L_pred, call_user_func($GLOBALS['first'], $__L_coll));
if ($__L_result) { return $__L_result;} else { $__L_coll = call_user_func($GLOBALS['next'], $__L_coll); continue;}} break; }
});
$some = &$GLOBALS['some'];
$GLOBALS['not_every_QMARK_'] = (function($__L_pred, $__L_coll) { return call_user_func($GLOBALS['not'], call_user_func($GLOBALS['every_QMARK_'], $__L_pred, $__L_coll));});
$not_every_QMARK_ = &$GLOBALS['not_every_QMARK_'];
$GLOBALS['not_any_QMARK_'] = (function($__L_pred, $__L_coll) { return call_user_func($GLOBALS['not'], call_user_func($GLOBALS['some'], $__L_pred, $__L_coll));});
$not_any_QMARK_ = &$GLOBALS['not_any_QMARK_'];
$GLOBALS['constantly'] = (function($__L_x) { return (function(...$__L_args) use (&$__L_x) { return $__L_x;});});
$constantly = &$GLOBALS['constantly'];
$GLOBALS['complement'] = (function($__L_f) { return (function(...$__L_args) use (&$__L_f) { return call_user_func($GLOBALS['not'], call_user_func($GLOBALS['apply'], $__L_f, $__L_args));});});
$complement = &$GLOBALS['complement'];
$GLOBALS['juxt'] = (function(...$__L_fs) { return (function(...$__L_args) use (&$__L_fs) { return call_user_func($GLOBALS['map'], (function($__L_f) use (&$__L_fs, &$__L_args) { return call_user_func($GLOBALS['apply'], $__L_f, $__L_args);}), $__L_fs);});});
$juxt = &$GLOBALS['juxt'];
$GLOBALS['fnil'] = (function($__L_f, $__L_x) { return (function($__L_arg, ...$__L_args) use (&$__L_x, &$__L_f) { return call_user_func($GLOBALS['apply'], $__L_f, (call_user_func($GLOBALS['nil_QMARK_'], $__L_arg) ? $__L_x : $__L_arg), $__L_args);});});
$fnil = &$GLOBALS['fnil'];
$GLOBALS['memoize'] = (function($__L_f) { $__L_cache = call_user_func($GLOBALS['atom'], \Clojure\Php\hashMap());
return (function(...$__L_args) use (&$__L_cache, &$__L_f) { $__L_key = call_user_func($GLOBALS['apply'], $GLOBALS['vector'], $__L_args);
$__L_cached = call_user_func($GLOBALS['get'], call_user_func($GLOBALS['deref'], $__L_cache), $__L_key);
if (call_user_func($GLOBALS['some_QMARK_'], $__L_cached)) { return $__L_cached;} else { $__L_result = call_user_func($GLOBALS['apply'], $__L_f, $__L_args);
call_user_func($GLOBALS['swap_BANG_'], $__L_cache, $GLOBALS['assoc'], $__L_key, $__L_result);
return $__L_result;}});});
$memoize = &$GLOBALS['memoize'];
$GLOBALS['compare'] = (function($__L_x, $__L_y) { if (($__L_x < $__L_y)) { return -1;} else { if (($__L_x > $__L_y)) { return 1;} else { if (\Clojure\Php\Kw::create('else')) { return 0;} else { return null;}}}});
$compare = &$GLOBALS['compare'];
$GLOBALS['identical_QMARK_'] = (function($__L_x, $__L_y) { return ($__L_x === $__L_y);});
$identical_QMARK_ = &$GLOBALS['identical_QMARK_'];
$GLOBALS['name'] = (function($__L_x) { if (call_user_func($GLOBALS['keyword_QMARK_'], $__L_x)) { return $__L_x->getName();} else { if (call_user_func($GLOBALS['symbol_QMARK_'], $__L_x)) { return strval($__L_x);} else { if (call_user_func($GLOBALS['string_QMARK_'], $__L_x)) { return $__L_x;} else { if (\Clojure\Php\Kw::create('else')) { return strval($__L_x);} else { return null;}}}}});
$name = &$GLOBALS['name'];
$GLOBALS['namespace'] = (function($__L_x) { if (call_user_func($GLOBALS['keyword_QMARK_'], $__L_x)) { return $__L_x->getNamespace();}});
$namespace = &$GLOBALS['namespace'];
$GLOBALS['subs'] = (function(...$__args) { $__n = count($__args); if ($__n == 3) { $__L_s = $__args[0]; $__L_start = $__args[1]; $__L_end = $__args[2]; return substr($__L_s, $__L_start, ($__L_end - $__L_start)); } else if ($__n == 2) { $__L_s = $__args[0]; $__L_start = $__args[1]; return substr($__L_s, $__L_start); } else { throw new \InvalidArgumentException('Wrong number of args: ' . $__n); } });
$subs = &$GLOBALS['subs'];
$GLOBALS['interleave'] = (function(...$__args) { $__n = count($__args); if ($__n == 2) { $__L_c1 = $__args[0]; $__L_c2 = $__args[1]; $__L_c1 = $__L_c1;
$__L_c2 = $__L_c2;
$__L_result = \Clojure\Php\vec();
 while(true) { if ((call_user_func($GLOBALS['seq'], $__L_c1) ? call_user_func($GLOBALS['seq'], $__L_c2) : null)) { $__L_c1 = call_user_func($GLOBALS['next'], $__L_c1); $__L_c2 = call_user_func($GLOBALS['next'], $__L_c2); $__L_result = call_user_func($GLOBALS['conj'], call_user_func($GLOBALS['conj'], $__L_result, call_user_func($GLOBALS['first'], $__L_c1)), call_user_func($GLOBALS['first'], $__L_c2)); continue;} else { return $__L_result;} break; }
 } else if ($__n >= 2) { $__L_c1 = $__args[0]; $__L_c2 = $__args[1]; $__L_colls = array_slice($__args, 2); $__L_colls = call_user_func($GLOBALS['cons'], $__L_c1, call_user_func($GLOBALS['cons'], $__L_c2, $__L_colls));
$__L_result = \Clojure\Php\vec();
 while(true) { if (call_user_func($GLOBALS['every_QMARK_'], $GLOBALS['seq'], $__L_colls)) { $__L_colls = call_user_func($GLOBALS['map'], $GLOBALS['next'], $__L_colls); $__L_result = call_user_func($GLOBALS['into'], $__L_result, call_user_func($GLOBALS['map'], $GLOBALS['first'], $__L_colls)); continue;} else { return $__L_result;} break; }
 } else { throw new \InvalidArgumentException('Wrong number of args: ' . $__n); } });
$interleave = &$GLOBALS['interleave'];
$GLOBALS['interpose'] = (function($__L_sep, $__L_coll) { $__L_coll = $__L_coll;
$__L_result = \Clojure\Php\vec();
$__L_first_QMARK_ = true;
 while(true) { if (call_user_func($GLOBALS['seq'], $__L_coll)) { if ($__L_first_QMARK_) { $__L_coll = call_user_func($GLOBALS['next'], $__L_coll); $__L_result = call_user_func($GLOBALS['conj'], $__L_result, call_user_func($GLOBALS['first'], $__L_coll)); $__L_first_QMARK_ = false; continue;} else { $__L_coll = call_user_func($GLOBALS['next'], $__L_coll); $__L_result = call_user_func($GLOBALS['conj'], call_user_func($GLOBALS['conj'], $__L_result, $__L_sep), call_user_func($GLOBALS['first'], $__L_coll)); $__L_first_QMARK_ = false; continue;}} else { return $__L_result;} break; }
});
$interpose = &$GLOBALS['interpose'];
$GLOBALS['flatten'] = (function($__L_coll) { $__L_coll = $__L_coll;
$__L_result = \Clojure\Php\vec();
 while(true) { if (call_user_func($GLOBALS['seq'], $__L_coll)) { $__L_x = call_user_func($GLOBALS['first'], $__L_coll);
if (call_user_func($GLOBALS['coll_QMARK_'], $__L_x)) { $__L_coll = call_user_func($GLOBALS['next'], $__L_coll); $__L_result = call_user_func($GLOBALS['into'], $__L_result, call_user_func($GLOBALS['flatten'], $__L_x)); continue;} else { $__L_coll = call_user_func($GLOBALS['next'], $__L_coll); $__L_result = call_user_func($GLOBALS['conj'], $__L_result, $__L_x); continue;}} else { return $__L_result;} break; }
});
$flatten = &$GLOBALS['flatten'];
$GLOBALS['mapcat'] = (function($__L_f, $__L_coll) { return call_user_func($GLOBALS['apply'], $GLOBALS['concat'], call_user_func($GLOBALS['map'], $__L_f, $__L_coll));});
$mapcat = &$GLOBALS['mapcat'];
$GLOBALS['keep'] = (function($__L_f, $__L_coll) { $__L_coll = $__L_coll;
$__L_result = \Clojure\Php\vec();
 while(true) { if (call_user_func($GLOBALS['seq'], $__L_coll)) { $__L_v = call_user_func($__L_f, call_user_func($GLOBALS['first'], $__L_coll));
$__L_coll = call_user_func($GLOBALS['next'], $__L_coll); $__L_result = (call_user_func($GLOBALS['nil_QMARK_'], $__L_v) ? $__L_result : call_user_func($GLOBALS['conj'], $__L_result, $__L_v)); continue;} else { return $__L_result;} break; }
});
$keep = &$GLOBALS['keep'];
$GLOBALS['keep_indexed'] = (function($__L_f, $__L_coll) { $__L_coll = $__L_coll;
$__L_idx = 0;
$__L_result = \Clojure\Php\vec();
 while(true) { if (call_user_func($GLOBALS['seq'], $__L_coll)) { $__L_v = call_user_func($__L_f, $__L_idx, call_user_func($GLOBALS['first'], $__L_coll));
$__L_coll = call_user_func($GLOBALS['next'], $__L_coll); $__L_idx = call_user_func($GLOBALS['inc'], $__L_idx); $__L_result = (call_user_func($GLOBALS['nil_QMARK_'], $__L_v) ? $__L_result : call_user_func($GLOBALS['conj'], $__L_result, $__L_v)); continue;} else { return $__L_result;} break; }
});
$keep_indexed = &$GLOBALS['keep_indexed'];
$GLOBALS['map_indexed'] = (function($__L_f, $__L_coll) { $__L_coll = $__L_coll;
$__L_idx = 0;
$__L_result = \Clojure\Php\vec();
 while(true) { if (call_user_func($GLOBALS['seq'], $__L_coll)) { $__L_coll = call_user_func($GLOBALS['next'], $__L_coll); $__L_idx = call_user_func($GLOBALS['inc'], $__L_idx); $__L_result = call_user_func($GLOBALS['conj'], $__L_result, call_user_func($__L_f, $__L_idx, call_user_func($GLOBALS['first'], $__L_coll))); continue;} else { return $__L_result;} break; }
});
$map_indexed = &$GLOBALS['map_indexed'];
$GLOBALS['partition_by'] = (function($__L_f, $__L_coll) { $__L_coll = $__L_coll;
$__L_result = \Clojure\Php\vec();
$__L_current = \Clojure\Php\vec();
$__L_current_val = null;
 while(true) { if (call_user_func($GLOBALS['seq'], $__L_coll)) { $__L_x = call_user_func($GLOBALS['first'], $__L_coll);
$__L_v = call_user_func($__L_f, $__L_x);
if ((call_user_func($GLOBALS['nil_QMARK_'], $__L_current_val) ? call_user_func($GLOBALS['nil_QMARK_'], $__L_current_val) : call_user_func($GLOBALS['_EQ_'], $__L_v, $__L_current_val))) { $__L_coll = call_user_func($GLOBALS['next'], $__L_coll); $__L_result = $__L_result; $__L_current = call_user_func($GLOBALS['conj'], $__L_current, $__L_x); $__L_current_val = $__L_v; continue;} else { $__L_coll = call_user_func($GLOBALS['next'], $__L_coll); $__L_result = call_user_func($GLOBALS['conj'], $__L_result, $__L_current); $__L_current = \Clojure\Php\vec($__L_x); $__L_current_val = $__L_v; continue;}} else { if (call_user_func($GLOBALS['seq'], $__L_current)) { return call_user_func($GLOBALS['conj'], $__L_result, $__L_current);} else { return $__L_result;}} break; }
});
$partition_by = &$GLOBALS['partition_by'];
$GLOBALS['split_at'] = (function($__L_n, $__L_coll) { return \Clojure\Php\vec(call_user_func($GLOBALS['take'], $__L_n, $__L_coll), call_user_func($GLOBALS['drop'], $__L_n, $__L_coll));});
$split_at = &$GLOBALS['split_at'];
$GLOBALS['split_with'] = (function($__L_pred, $__L_coll) { return \Clojure\Php\vec(call_user_func($GLOBALS['take_while'], $__L_pred, $__L_coll), call_user_func($GLOBALS['drop_while'], $__L_pred, $__L_coll));});
$split_with = &$GLOBALS['split_with'];
$GLOBALS['butlast'] = (function($__L_coll) { $__L_coll = $__L_coll;
$__L_result = \Clojure\Php\vec();
 while(true) { if (call_user_func($GLOBALS['next'], $__L_coll)) { $__L_coll = call_user_func($GLOBALS['next'], $__L_coll); $__L_result = call_user_func($GLOBALS['conj'], $__L_result, call_user_func($GLOBALS['first'], $__L_coll)); continue;} else { return $__L_result;} break; }
});
$butlast = &$GLOBALS['butlast'];
$GLOBALS['shuffle'] = (function($__L_coll) { $__L_arr = call_user_func('\Clojure\Php\toArray', $__L_coll);
shuffle($__L_arr);
return call_user_func('\Clojure\Php\vector', $__L_arr);});
$shuffle = &$GLOBALS['shuffle'];
$GLOBALS['union'] = (function($__L_s1, $__L_s2) { return call_user_func($GLOBALS['reduce'], $GLOBALS['conj'], $__L_s1, $__L_s2);});
$union = &$GLOBALS['union'];
$GLOBALS['intersection'] = (function($__L_s1, $__L_s2) { return call_user_func($GLOBALS['reduce'], (function($__L_result, $__L_x) use (&$__L_s1, &$__L_s2) { if (call_user_func($GLOBALS['contains_QMARK_'], $__L_s2, $__L_x)) { return call_user_func($GLOBALS['conj'], $__L_result, $__L_x);} else { return $__L_result;}}), \Clojure\Php\hashSet(), $__L_s1);});
$intersection = &$GLOBALS['intersection'];
$GLOBALS['difference'] = (function($__L_s1, $__L_s2) { return call_user_func($GLOBALS['reduce'], (function($__L_result, $__L_x) use (&$__L_s1, &$__L_s2) { if (call_user_func($GLOBALS['contains_QMARK_'], $__L_s2, $__L_x)) { return $__L_result;} else { return call_user_func($GLOBALS['conj'], $__L_result, $__L_x);}}), \Clojure\Php\hashSet(), $__L_s1);});
$difference = &$GLOBALS['difference'];
$GLOBALS['subset_QMARK_'] = (function($__L_s1, $__L_s2) { return call_user_func($GLOBALS['every_QMARK_'], (function($__L_x) use (&$__L_s1, &$__L_s2) { return call_user_func($GLOBALS['contains_QMARK_'], $__L_s2, $__L_x);}), $__L_s1);});
$subset_QMARK_ = &$GLOBALS['subset_QMARK_'];
$GLOBALS['superset_QMARK_'] = (function($__L_s1, $__L_s2) { return call_user_func($GLOBALS['subset_QMARK_'], $__L_s2, $__L_s1);});
$superset_QMARK_ = &$GLOBALS['superset_QMARK_'];
$GLOBALS['max'] = (function(...$__L_xs) { return call_user_func($GLOBALS['reduce'], (function($__L_a, $__L_b) use (&$__L_xs) { if (($__L_a > $__L_b)) { return $__L_a;} else { return $__L_b;}}), call_user_func($GLOBALS['first'], $__L_xs), call_user_func($GLOBALS['next'], $__L_xs));});
$max = &$GLOBALS['max'];
$GLOBALS['min'] = (function(...$__L_xs) { return call_user_func($GLOBALS['reduce'], (function($__L_a, $__L_b) use (&$__L_xs) { if (($__L_a < $__L_b)) { return $__L_a;} else { return $__L_b;}}), call_user_func($GLOBALS['first'], $__L_xs), call_user_func($GLOBALS['next'], $__L_xs));});
$min = &$GLOBALS['min'];
$GLOBALS['abs'] = (function($__L_x) { if (($__L_x < 0)) { return (-$__L_x);} else { return $__L_x;}});
$abs = &$GLOBALS['abs'];
$GLOBALS['mod'] = (function($__L_n, $__L_d) { return ($__L_n % $__L_d);});
$mod = &$GLOBALS['mod'];
$GLOBALS['quot'] = (function($__L_n, $__L_d) { return intdiv($__L_n, $__L_d);});
$quot = &$GLOBALS['quot'];
$GLOBALS['rem'] = (function($__L_n, $__L_d) { return ($__L_n % $__L_d);});
$rem = &$GLOBALS['rem'];
$GLOBALS['even_QMARK_'] = (function($__L_n) { return (0 === ($__L_n % 2));});
$even_QMARK_ = &$GLOBALS['even_QMARK_'];
$GLOBALS['odd_QMARK_'] = (function($__L_n) { return call_user_func($GLOBALS['not'], call_user_func($GLOBALS['even_QMARK_'], $__L_n));});
$odd_QMARK_ = &$GLOBALS['odd_QMARK_'];
$GLOBALS['pos_QMARK_'] = (function($__L_n) { return ($__L_n > 0);});
$pos_QMARK_ = &$GLOBALS['pos_QMARK_'];
$GLOBALS['neg_QMARK_'] = (function($__L_n) { return ($__L_n < 0);});
$neg_QMARK_ = &$GLOBALS['neg_QMARK_'];
$GLOBALS['zero_QMARK_'] = (function($__L_n) { return ($__L_n === 0);});
$zero_QMARK_ = &$GLOBALS['zero_QMARK_'];
$GLOBALS['rand'] = (function() { return (rand() / getrandmax());});
$rand = &$GLOBALS['rand'];
$GLOBALS['rand_int'] = (function($__L_n) { return rand(0, call_user_func($GLOBALS['dec'], $__L_n));});
$rand_int = &$GLOBALS['rand_int'];
$GLOBALS['rand_nth'] = (function($__L_coll) { return call_user_func($GLOBALS['nth'], $__L_coll, call_user_func($GLOBALS['rand_int'], call_user_func($GLOBALS['count'], $__L_coll)));});
$rand_nth = &$GLOBALS['rand_nth'];
$GLOBALS['read_string'] = (function($__L_s) { 'Parse an EDN string. Currently uses PHP\'s json_decode for JSON-compatible values.';
return json_decode($__L_s, true);});
$read_string = &$GLOBALS['read_string'];
$GLOBALS['ex_info'] = (function(...$__args) { $__n = count($__args); if ($__n == 3) { $__L_msg = $__args[0]; $__L_data = $__args[1]; $__L_cause = $__args[2]; return call_user_func('\Clojure\Php\exInfo', $__L_msg, $__L_data, $__L_cause); } else if ($__n == 2) { $__L_msg = $__args[0]; $__L_data = $__args[1]; return call_user_func('\Clojure\Php\exInfo', $__L_msg, $__L_data); } else { throw new \InvalidArgumentException('Wrong number of args: ' . $__n); } });
$ex_info = &$GLOBALS['ex_info'];
$GLOBALS['ex_data'] = (function($__L_ex) { return call_user_func('\Clojure\Php\exData', $__L_ex);});
$ex_data = &$GLOBALS['ex_data'];
$GLOBALS['ex_message'] = (function($__L_ex) { return call_user_func('\Clojure\Php\exMessage', $__L_ex);});
$ex_message = &$GLOBALS['ex_message'];
$GLOBALS['ex_cause'] = (function($__L_ex) { return call_user_func('\Clojure\Php\exCause', $__L_ex);});
$ex_cause = &$GLOBALS['ex_cause'];
$GLOBALS['Throwable__GT_map'] = (function($__L_ex) { if (call_user_func($GLOBALS['nil_QMARK_'], $__L_ex)) { return null;} else { $__L_data = call_user_func($GLOBALS['ex_data'], $__L_ex);
$__L_msg = call_user_func($GLOBALS['ex_message'], $__L_ex);
$__L_cause = call_user_func($GLOBALS['ex_cause'], $__L_ex);
$__L_class_name = get_class($__L_ex);
return \Clojure\Php\hashMap(\Clojure\Php\Kw::create('type'), $__L_class_name, \Clojure\Php\Kw::create('message'), $__L_msg, \Clojure\Php\Kw::create('data'), $__L_data, \Clojure\Php\Kw::create('cause'), ($__L_cause ? call_user_func($GLOBALS['Throwable__GT_map'], $__L_cause) : null));}});
$Throwable__GT_map = &$GLOBALS['Throwable__GT_map'];
$GLOBALS['ex_triage'] = (function($__L_throwable_map) { $__L___dest_1 = $__L_throwable_map;
$__L_type = call_user_func($GLOBALS['get'], $__L___dest_1, \Clojure\Php\Kw::create('type'));
$__L_message = call_user_func($GLOBALS['get'], $__L___dest_1, \Clojure\Php\Kw::create('message'));
$__L_data = call_user_func($GLOBALS['get'], $__L___dest_1, \Clojure\Php\Kw::create('data'));
$__L_cause = call_user_func($GLOBALS['get'], $__L___dest_1, \Clojure\Php\Kw::create('cause'));
$__L_phase = (call_user_func($GLOBALS['get'], $__L_data, \Clojure\Php\Kw::createNs('cljp.error', 'phase')) ? call_user_func($GLOBALS['get'], $__L_data, \Clojure\Php\Kw::createNs('cljp.error', 'phase')) : \Clojure\Php\Kw::create('execution'));
$__L_err_type = call_user_func($GLOBALS['get'], $__L_data, \Clojure\Php\Kw::createNs('cljp.error', 'type'));
$__L_file = call_user_func($GLOBALS['get'], $__L_data, \Clojure\Php\Kw::createNs('cljp.error', 'file'));
$__L_line = call_user_func($GLOBALS['get'], $__L_data, \Clojure\Php\Kw::createNs('cljp.error', 'line'));
$__L_col = call_user_func($GLOBALS['get'], $__L_data, \Clojure\Php\Kw::createNs('cljp.error', 'column'));
$__L_sym = call_user_func($GLOBALS['get'], $__L_data, \Clojure\Php\Kw::createNs('cljp.error', 'symbol'));
$__L_hint = call_user_func($GLOBALS['get'], $__L_data, \Clojure\Php\Kw::createNs('cljp.error', 'hint'));
return \Clojure\Php\hashMap(\Clojure\Php\Kw::createNs('cljp.error', 'file'), $__L_file, \Clojure\Php\Kw::createNs('cljp.error', 'type'), $__L_err_type, \Clojure\Php\Kw::createNs('cljp.error', 'column'), $__L_col, \Clojure\Php\Kw::createNs('cljp.error', 'message'), $__L_message, \Clojure\Php\Kw::createNs('cljp.error', 'line'), $__L_line, \Clojure\Php\Kw::createNs('cljp.error', 'phase'), $__L_phase, \Clojure\Php\Kw::createNs('cljp.error', 'hint'), $__L_hint, \Clojure\Php\Kw::createNs('cljp.error', 'class'), $__L_type, \Clojure\Php\Kw::createNs('cljp.error', 'cause'), ($__L_cause ? call_user_func($GLOBALS['ex_message'], \Clojure\Php\hashMap(\Clojure\Php\Kw::create('message'), call_user_func(\Clojure\Php\Kw::create('message'), $__L_cause))) : null), \Clojure\Php\Kw::createNs('cljp.error', 'symbol'), $__L_sym);});
$ex_triage = &$GLOBALS['ex_triage'];
$GLOBALS['ex_str'] = (function($__L_triage_data) { $__L_phase = call_user_func($GLOBALS['get'], $__L_triage_data, \Clojure\Php\Kw::createNs('cljp.error', 'phase'));
$__L_err_type = call_user_func($GLOBALS['get'], $__L_triage_data, \Clojure\Php\Kw::createNs('cljp.error', 'type'));
$__L_class = call_user_func($GLOBALS['get'], $__L_triage_data, \Clojure\Php\Kw::createNs('cljp.error', 'class'));
$__L_message = call_user_func($GLOBALS['get'], $__L_triage_data, \Clojure\Php\Kw::createNs('cljp.error', 'message'));
$__L_file = call_user_func($GLOBALS['get'], $__L_triage_data, \Clojure\Php\Kw::createNs('cljp.error', 'file'));
$__L_line = call_user_func($GLOBALS['get'], $__L_triage_data, \Clojure\Php\Kw::createNs('cljp.error', 'line'));
$__L_column = call_user_func($GLOBALS['get'], $__L_triage_data, \Clojure\Php\Kw::createNs('cljp.error', 'column'));
$__L_symbol = call_user_func($GLOBALS['get'], $__L_triage_data, \Clojure\Php\Kw::createNs('cljp.error', 'symbol'));
$__L_hint = call_user_func($GLOBALS['get'], $__L_triage_data, \Clojure\Php\Kw::createNs('cljp.error', 'hint'));
$__L_loc = call_user_func($GLOBALS['str'], ($__L_file ? $__L_file : 'REPL'), ':', ($__L_line ? $__L_line : 1), ($__L_column ? call_user_func($GLOBALS['str'], ':', $__L_column) : ''));
$__L_class_str = ($__L_class ? call_user_func($GLOBALS['str'], $__L_class) : '');
$__L_class_simple = basename(str_replace('\\', '/', $__L_class_str));
$__L_type_str = ($__L_err_type ? ltrim(call_user_func($GLOBALS['str'], $__L_err_type), ':') : '');
$__L_type_label = ($__L_err_type ? call_user_func($GLOBALS['str'], ucfirst($__L_type_str), 'Error') : ($__L_class ? $__L_class_simple : 'Error'));
return call_user_func($GLOBALS['str'], $__L_type_label, ': ', $__L_message, ' at (', $__L_loc, ')', ($__L_hint ? call_user_func($GLOBALS['str'], '
Hint: ', $__L_hint) : ''));});
$ex_str = &$GLOBALS['ex_str'];
$GLOBALS['err__GT_msg'] = (function($__L_ex) { return call_user_func($GLOBALS['ex_str'], call_user_func($GLOBALS['ex_triage'], call_user_func($GLOBALS['Throwable__GT_map'], $__L_ex)));});
$err__GT_msg = &$GLOBALS['err__GT_msg'];
$GLOBALS['_STAR_1'] = null;
$_STAR_1 = &$GLOBALS['_STAR_1'];
$GLOBALS['_STAR_2'] = null;
$_STAR_2 = &$GLOBALS['_STAR_2'];
$GLOBALS['_STAR_3'] = null;
$_STAR_3 = &$GLOBALS['_STAR_3'];
$GLOBALS['_STAR_e'] = null;
$_STAR_e = &$GLOBALS['_STAR_e'];
$GLOBALS['_STAR_ns_STAR_'] = 'user';
$_STAR_ns_STAR_ = &$GLOBALS['_STAR_ns_STAR_'];
$GLOBALS['_STAR_print_length_STAR_'] = null;
$_STAR_print_length_STAR_ = &$GLOBALS['_STAR_print_length_STAR_'];
$GLOBALS['_STAR_print_level_STAR_'] = null;
$_STAR_print_level_STAR_ = &$GLOBALS['_STAR_print_level_STAR_'];
$GLOBALS['_STAR_print_meta_STAR_'] = null;
$_STAR_print_meta_STAR_ = &$GLOBALS['_STAR_print_meta_STAR_'];
$GLOBALS['_push_repl_result'] = (function($__L_value) { 'Internal: Update REPL result history.';
return $__L_value;});
$_push_repl_result = &$GLOBALS['_push_repl_result'];
$GLOBALS['symbol'] = (function(...$__args) { $__n = count($__args); if ($__n == 2) { $__L_ns = $__args[0]; $__L_name = $__args[1]; return call_user_func('\Clojure\Php\sym', $__L_name, $__L_ns); } else if ($__n == 1) { $__L_name = $__args[0]; return call_user_func('\Clojure\Php\sym', $__L_name); } else { throw new \InvalidArgumentException('Wrong number of args: ' . $__n); } });
$symbol = &$GLOBALS['symbol'];
$GLOBALS['format'] = (function($__L_fmt, ...$__L_args) { return call_user_func_array('sprintf', call_user_func($GLOBALS['cons'], $__L_fmt, $__L_args));});
$format = &$GLOBALS['format'];
$GLOBALS['realized_QMARK_'] = (function($__L_x) { if (method_exists($__L_x, 'isRealized')) { return $__L_x->isRealized();} else { return true;}});
$realized_QMARK_ = &$GLOBALS['realized_QMARK_'];
$GLOBALS['doall'] = (function(...$__args) { $__n = count($__args); if ($__n == 2) { $__L_n = $__args[0]; $__L_coll = $__args[1]; if ($__L_n) { $__L_i = $__L_n;
$__L_s = call_user_func($GLOBALS['seq'], $__L_coll);
 while(true) { if ((($__L_i > 0) ? $__L_s : null)) { $__L_i = call_user_func($GLOBALS['dec'], $__L_i); $__L_s = call_user_func($GLOBALS['next'], $__L_s); continue;}
 break; }
} else { $__L_s = call_user_func($GLOBALS['seq'], $__L_coll);
 while(true) { if ($__L_s) { $__L_s = call_user_func($GLOBALS['next'], $__L_s); continue;}
 break; }
}
return $__L_coll; } else if ($__n == 1) { $__L_coll = $__args[0]; return call_user_func($GLOBALS['doall'], $__L_coll, null); } else { throw new \InvalidArgumentException('Wrong number of args: ' . $__n); } });
$doall = &$GLOBALS['doall'];
$GLOBALS['dorun'] = (function(...$__args) { $__n = count($__args); if ($__n == 2) { $__L_n = $__args[0]; $__L_coll = $__args[1]; $__L_i = $__L_n;
$__L_s = call_user_func($GLOBALS['seq'], $__L_coll);
 while(true) { if ((($__L_i > 0) ? $__L_s : null)) { $__L_i = call_user_func($GLOBALS['dec'], $__L_i); $__L_s = call_user_func($GLOBALS['next'], $__L_s); continue;}
 break; }
return null; } else if ($__n == 1) { $__L_coll = $__args[0]; $__L_s = call_user_func($GLOBALS['seq'], $__L_coll);
 while(true) { if ($__L_s) { $__L_s = call_user_func($GLOBALS['next'], $__L_s); continue;}
 break; }
return null; } else { throw new \InvalidArgumentException('Wrong number of args: ' . $__n); } });
$dorun = &$GLOBALS['dorun'];
$GLOBALS['re_pattern'] = (function($__L_s) { if (is_string($__L_s)) { return $__L_s;} else { throw (new \InvalidArgumentException('re-pattern requires a string'));
}});
$re_pattern = &$GLOBALS['re_pattern'];
$GLOBALS['re_matches'] = (function($__L_re, $__L_s) { $__L_result = array();
$__L_matched = preg_match(call_user_func($GLOBALS['str'], '^', $__L_re, '$'), $__L_s, $__L_result);
if (($__L_matched > 0)) { if ((1 === count($__L_result))) { return call_user_func($GLOBALS['first'], $__L_result);} else { return call_user_func('\Clojure\Php\vec', $__L_result);}}});
$re_matches = &$GLOBALS['re_matches'];
$GLOBALS['re_find'] = (function($__L_re, $__L_s) { $__L_result = array();
$__L_matched = preg_match($__L_re, $__L_s, $__L_result);
if (($__L_matched > 0)) { if ((1 === count($__L_result))) { return call_user_func($GLOBALS['first'], $__L_result);} else { return call_user_func('\Clojure\Php\vec', $__L_result);}}});
$re_find = &$GLOBALS['re_find'];
$GLOBALS['re_seq'] = (function($__L_re, $__L_s) { $__L_result = array();
$__L__ = preg_match_all($__L_re, $__L_s, $__L_result);
if ((count(call_user_func($GLOBALS['first'], $__L_result)) > 0)) { return call_user_func('\Clojure\Php\vec', call_user_func($GLOBALS['first'], $__L_result));}});
$re_seq = &$GLOBALS['re_seq'];
$GLOBALS['re_groups'] = (function($__L_m) { if (call_user_func($GLOBALS['string_QMARK_'], $__L_m)) { return $__L_m;} else { if ((call_user_func($GLOBALS['count'], $__L_m) > 1)) { return $__L_m;} else { return call_user_func($GLOBALS['first'], $__L_m);}}});
$re_groups = &$GLOBALS['re_groups'];
$GLOBALS['line_seq'] = (function($__L_rdr) { return (new \Clojure\Php\LazySeq((function() use (&$__L_rdr) { $__L_line = fgets($__L_rdr);
if (($__L_line !== false)) { return call_user_func($GLOBALS['cons'], rtrim($__L_line, PHP_EOL), call_user_func($GLOBALS['line_seq'], $__L_rdr));}})));});
$line_seq = &$GLOBALS['line_seq'];
$GLOBALS['tree_seq'] = (function($__L_branch_QMARK_, $__L_children, $__L_root) { $__L_walk = (function($__L_node) use (&$__L_branch_QMARK_, &$__L_children, &$__L_root) { return (new \Clojure\Php\LazySeq((function() use (&$__L_branch_QMARK_, &$__L_children, &$__L_node, &$__L_root) { return call_user_func($GLOBALS['cons'], $__L_node, (call_user_func($__L_branch_QMARK_, $__L_node) ? call_user_func($GLOBALS['mapcat'], $GLOBALS['walk'], call_user_func($__L_children, $__L_node)) : null));})));});
return call_user_func($__L_walk, $__L_root);});
$tree_seq = &$GLOBALS['tree_seq'];
$GLOBALS['file_seq'] = (function($__L_dir) { return call_user_func($GLOBALS['tree_seq'], (function($__L_f) use (&$__L_dir) { return is_dir($__L_f);}), (function($__L_d) use (&$__L_dir) { $__L_files = scandir($__L_d);
return call_user_func($GLOBALS['filter'], (function($__L_f) use (&$__L_dir, &$__L_files, &$__L_d) { return call_user_func($GLOBALS['not'], (call_user_func($GLOBALS['_EQ_'], $__L_f, '.') ? call_user_func($GLOBALS['_EQ_'], $__L_f, '.') : call_user_func($GLOBALS['_EQ_'], $__L_f, '..')));}), call_user_func($GLOBALS['map'], (function($__L_f) use (&$__L_dir, &$__L_files, &$__L_d) { return call_user_func($GLOBALS['str'], $__L_d, '/', $__L_f);}), $__L_files));}), $__L_dir);});
$file_seq = &$GLOBALS['file_seq'];
$GLOBALS['xml_seq'] = (function($__L_root) { return call_user_func($GLOBALS['tree_seq'], (function($__L_node) use (&$__L_root) { if (call_user_func($GLOBALS['map_QMARK_'], $__L_node)) { return call_user_func($GLOBALS['contains_QMARK_'], $__L_node, \Clojure\Php\Kw::create('content'));}}), (function($__L_node) use (&$__L_root) { return call_user_func($GLOBALS['get'], $__L_node, \Clojure\Php\Kw::create('content'));}), $__L_root);});
$xml_seq = &$GLOBALS['xml_seq'];
echo('Hello from ClojurePHP!
');
echo((1 + 2));
echo('
');
echo((true ? 'yes' : 'no'));
echo('
');
$__L_x = 10;
$__L_y = 20;
echo(($__L_x + $__L_y));
echo('
');
echo((new Exception('Test Exception'))->getMessage());
echo('
');
